{
	"id": 135121479,
	"number": 14432,
	"state": "closed",
	"title": "runtime: error returned by os.OpenFile blocks panic handler",
	"body": "go1.6 windows/amd64 on Windows 8\r\n\r\nThe following program tries to create a new file with os.O_EXCL and panics if the file already exists. When `panic(err)` is called, \"panic:\" is written to stderr and the program blocks. You have to terminate it with Ctrl-C. If you uncomment err.Error() then you get a normal backtrace and the program exits.\r\n\r\nI'm guessing that there is a problem with retrieving the error information in the panic handler, but if done before panicking, then everything works as expected.\r\n\r\n```go\r\npackage main\r\n\r\nimport \"os\"\r\n\r\nfunc main() {\r\n\t_, err := os.OpenFile(\"tmp\", os.O_RDWR|os.O_CREATE|os.O_EXCL, 0666)\r\n\tif err != nil {\r\n\t\t//err.Error()\r\n\t\tpanic(err)\r\n\t}\r\n}\r\n```",
	"user": {
		"login": "mxk",
		"id": 7256995,
		"type": "User",
		"site_admin": false
	},
	"assignee": {
		"login": "minux",
		"id": 135652,
		"type": "User",
		"site_admin": false
	},
	"comments": 8,
	"closed_at": "2016-02-21T20:19:09Z",
	"created_at": "2016-02-20T21:18:36Z",
	"updated_at": "2016-02-21T20:19:09Z",
	"milestone": {
		"id": 1414133,
		"number": 31,
		"title": "Go1.7"
	}
}
