{
	"id": 167659207,
	"number": 16502,
	"state": "open",
	"title": "testing: Document interaction of Skip and Error",
	"body": "```sh\r\ngo version go1.7rc3 linux/amd64\r\n```\r\n\r\n```go\r\npackage todo_test\r\n\r\nimport \"testing\"\r\n\r\nfunc TestIssueFixed(t *testing.T) {\r\n\tdefer func() {\r\n\t\tif t.Failed() {\r\n\t\t\tt.Skip(\"Test failed as expected; see issue XXXXXXXX.\")\r\n\t\t}\r\n\t\tt.Fatal(\"Test did not fail as expected; please update issue XXXXXXXX.\")\r\n\t}()\r\n\r\n\tt.Log(\"\u003cno symptoms of issue XXXXXXXX\u003e\")\r\n}\r\n\r\nfunc TestIssueOpen(t *testing.T) {\r\n\tdefer func() {\r\n\t\tif t.Failed() {\r\n\t\t\tt.Skip(\"Test failed as expected; see issue XXXXXXXX.\")\r\n\t\t}\r\n\t\tt.Fatal(\"Test did not fail as expected; please update issue XXXXXXXX.\")\r\n\t}()\r\n\r\n\tt.Error(\"\u003csymptom of issue XXXXXXXX\u003e\")\r\n}\r\n```\r\n\r\nExpected:\r\n```\r\n$ go test -v todo\r\n=== RUN   TestIssueFixed\r\n--- FAIL: TestIssueFixed (0.00s)\r\n        todo_test.go:13: \u003cno symptoms of issue XXXXXXXX\u003e\r\n        todo_test.go:10: Test did not fail as expected; please update issue XXXXXXXX.\r\n=== RUN   TestIssueOpen\r\n--- SKIP: TestIssueOpen (0.00s)\r\n        todo_test.go:24: \u003csymptom of issue XXXXXXXX\u003e\r\n        todo_test.go:19: Test failed as expected; see issue XXXXXXXX.\r\nFAIL\r\nexit status 1\r\nFAIL    todo    0.018s\r\n```\r\n\r\nActual:\r\n```\r\n$ go test -v todo\r\n=== RUN   TestIssueFixed\r\n--- FAIL: TestIssueFixed (0.00s)\r\n        todo_test.go:13: \u003cno symptoms of issue XXXXXXXX\u003e\r\n        todo_test.go:10: Test did not fail as expected; please update issue XXXXXXXX.\r\n=== RUN   TestIssueOpen\r\n--- FAIL: TestIssueOpen (0.00s)\r\n        todo_test.go:24: \u003csymptom of issue XXXXXXXX\u003e\r\n        todo_test.go:19: Test failed as expected; see issue XXXXXXXX.\r\nFAIL\r\nexit status 1\r\nFAIL    todo    0.031s\r\n```\r\n\r\nI'm guessing this is not actually a bug, but I don't see anything in https://golang.org/pkg/testing/ describing how Skip and Error are supposed to interact.  It doesn't seem unreasonable to think that a test could be Skipped after it has already Failed, but that turns out not to be the case as implemented.\r\n\r\nCould someone with more in-depth knowledge of the testing package please confirm whether this behavior is intended (and, if so, update the documentation)?",
	"user": {
		"login": "bcmills",
		"id": 5200974,
		"type": "User",
		"site_admin": false
	},
	"labels": [
		{
			"name": "Documentation"
		}
	],
	"assignee": {
		"login": "mpvl",
		"id": 6445383,
		"type": "User",
		"site_admin": false
	},
	"comments": 5,
	"created_at": "2016-07-26T17:00:47Z",
	"updated_at": "2016-09-09T10:52:08Z",
	"milestone": {
		"id": 1709363,
		"number": 38,
		"title": "Go1.8"
	}
}
