{
	"id": 66072657,
	"body": "\u003ca id=\"c3\"\u003e\u003c/a\u003eComment 3 by **vincent@callanan.ie**:\n\n\u003cpre\u003eI just happened to notice that the respository was in fact successfully retrieved in\nspite of the above error message. Is it possible that this error message is spurious or\njust related to the specific package. If so, apologies for taking your time on this.\u003c/pre\u003e",
	"user": {
		"login": "gopherbot",
		"id": 8566911,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2012-12-02T12:43:23Z",
	"updated_at": "2014-12-08T10:23:47Z"
}
