{
	"id": 168367059,
	"body": "I took a look at this.  I can throw and catch an exception in a constructor in cgo code.  However, I can not throw and catch an exception in cgo code after Go code starts.  This is true even if I comment out the call to initExceptionHandler in osinit, so it doesn't have anything to do with the exception handlers that the Go runtime installs.  The throw starts, but it is never caught.  There is something about the Go runtime, or having Go in the call stack, that causes Windows to be unable to find the installed SEH handler, even when the handler is in the same frame as the throw.  I've verified that we are using the external linker.\r\n\r\nI do not know how to fix this.",
	"user": {
		"login": "ianlancetaylor",
		"id": 3194333,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2016-01-02T05:50:21Z",
	"updated_at": "2016-01-02T05:50:21Z"
}
