{
	"id": 234113295,
	"body": "I just got a failure after 564 runs with that CL patched in.\r\n\r\n```\r\n--- FAIL: TestCgoExternalThreadSignal (60.03s)\r\n\tcrash_test.go:105: testprogcgo CgoExternalThreadSignal exit status: exit status 2\r\n\tcrash_cgo_test.go:116: expected \"OK\\n\", but got:\r\n\t\tSIGQUIT: quit\r\n\t\tPC=0x407475e m=0\r\n\t\t\r\n\t\tgoroutine 1 [syscall]:\r\n\t\tsyscall.Syscall6(0xad, 0x1, 0x564e, 0xc4200a6080, 0x24, 0x0, 0x0, 0x40c46a0, 0xc420059bb0, 0x40371de)\r\n\t\t\t/Users/josh/go/tip/src/syscall/asm_darwin_amd64.s:41 +0x5 fp=0xc420059b28 sp=0xc420059b20\r\n\t\tos.(*Process).blockUntilWaitable(0xc42007a300, 0x40e9c98, 0xc42009c000, 0xc42008a100)\r\n\t\t\t/Users/josh/go/tip/src/os/wait_waitid.go:28 +0xbc fp=0xc420059bc0 sp=0xc420059b28\r\n\t\tos.(*Process).wait(0xc42007a300, 0x0, 0x4015c6e, 0xc420088040)\r\n\t\t\t/Users/josh/go/tip/src/os/exec_unix.go:22 +0xab fp=0xc420059c50 sp=0xc420059bc0\r\n\t\tos.(*Process).Wait(0xc42007a300, 0xc420059cb8, 0x0, 0x0)\r\n\t\t\t/Users/josh/go/tip/src/os/doc.go:49 +0x2b fp=0xc420059c80 sp=0xc420059c50\r\n\t\tos/exec.(*Cmd).Wait(0xc42009c000, 0x0, 0x0)\r\n\t\t\t/Users/josh/go/tip/src/os/exec/exec.go:434 +0x6d fp=0xc420059d10 sp=0xc420059c80\r\n\t\tos/exec.(*Cmd).Run(0xc42009c000, 0xc42009e000, 0x3)\r\n\t\t\t/Users/josh/go/tip/src/os/exec/exec.go:279 +0x48 fp=0xc420059d38 sp=0xc420059d10\r\n\t\tos/exec.(*Cmd).CombinedOutput(0xc42009c000, 0x52, 0xc420059e50, 0x2, 0x2, 0xc42009c000)\r\n\t\t\t/Users/josh/go/tip/src/os/exec/exec.go:494 +0x13b fp=0xc420059d78 sp=0xc420059d38\r\n\t\tmain.CgoExternalThreadSignal()\r\n\t\t\t/Users/josh/go/tip/src/runtime/testdata/testprogcgo/threadprof.go:85 +0xe3 fp=0xc420059ea0 sp=0xc420059d78\r\n\t\tmain.main()\r\n\t\t\t/Users/josh/go/tip/src/runtime/testdata/testprogcgo/main.go:34 +0x1f1 fp=0xc420059f48 sp=0xc420059ea0\r\n\t\truntime.main()\r\n\t\t\t/Users/josh/go/tip/src/runtime/proc.go:183 +0x1f4 fp=0xc420059fa0 sp=0xc420059f48\r\n\t\truntime.goexit()\r\n\t\t\t/Users/josh/go/tip/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420059fa8 sp=0xc420059fa0\r\n\t\t\r\n\t\tgoroutine 17 [syscall, locked to thread]:\r\n\t\truntime.goexit()\r\n\t\t\t/Users/josh/go/tip/src/runtime/asm_amd64.s:2086 +0x1\r\n\t\t\r\n\t\tgoroutine 19 [syscall]:\r\n\t\tos/signal.signal_recv(0x0)\r\n\t\t\t/Users/josh/go/tip/src/runtime/sigqueue.go:116 +0x157\r\n```\r\n\r\nThe previous 6 failures were 1 TestCgoCCodeSIGPROF, 5 TestCgoExternalThreadSignal.\r\n\r\nI'm going to restart with just the TestCgoCCodeSIGPROF running.\r\n",
	"user": {
		"login": "josharian",
		"id": 67496,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2016-07-20T23:20:00Z",
	"updated_at": "2016-07-20T23:20:00Z"
}
